import {
  SiJavascript,
  SiTypescript,
  SiGithub,
  SiReact,
  SiReactquery,
  SiGit,
  SiCss3,
  SiHtml5,
  SiFirebase,
  SiPrisma,
  SiExpress,
  SiChakraui,
  SiStyledcomponents,
  SiPostgresql,
  SiNextdotjs,
  SiTailwindcss,
  SiRedux,
  SiReacthookform,
  SiCypress,
  SiPlaywright,
  SiFigma,
  SiExpo,
  SiAxios,
  SiGraphql
} from 'react-icons/si';
import { FaNodeJs } from 'react-icons/fa';
import { TbBrandReactNative } from 'react-icons/tb';
import { RestIcon } from '../icons/restIcon';
import { GiMonsteraLeaf } from 'react-icons/gi';

export enum IconName {
  GITHUB = 'github',
  TYPESCRIPT = 'typescript',
  JAVASCRIPT = 'javascript',
  REACT = 'react',
  REACT_NATIVE = 'reactNative',
  GIT = 'git',
  FIREBASE = 'firebase',
  EXPRESS = 'express',
  REACT_QUERY = 'react_query',
  CSS = 'css',
  HTML = 'html',
  PRISMA = 'prisma',
  CHAKRA = 'chakra',
  STYLED = 'styled',
  NODEJS = 'nodejs',
  POSTGRES = 'postgres',
  REST = 'rest',
  NEXT = 'next',
  TAILWIND = 'tailwind',
  REDUX = 'redux',
  REACT_HOOK_FORM = 'react_hook_form',
  MONSTERA = 'monstera',
  CYPRESS = 'cypress',
  PLAYWRIGHT = 'playwright',
  FIGMA = 'figma',
  EXPO = 'expo',
  AXIOS = 'axios',
  GRAPHQL = 'graphql'
}

export const IconMapper = {
  [IconName.GITHUB]: SiGithub,
  [IconName.TYPESCRIPT]: SiTypescript,
  [IconName.JAVASCRIPT]: SiJavascript,
  [IconName.REACT]: SiReact,
  [IconName.REACT_NATIVE]: TbBrandReactNative,
  [IconName.GIT]: SiGit,
  [IconName.REACT_QUERY]: SiReactquery,
  [IconName.FIREBASE]: SiFirebase,
  [IconName.EXPRESS]: SiExpress,
  [IconName.CSS]: SiCss3,
  [IconName.HTML]: SiHtml5,
  [IconName.PRISMA]: SiPrisma,
  [IconName.CHAKRA]: SiChakraui,
  [IconName.STYLED]: SiStyledcomponents,
  [IconName.NODEJS]: FaNodeJs,
  [IconName.POSTGRES]: SiPostgresql,
  [IconName.REST]: RestIcon,
  [IconName.TAILWIND]: SiTailwindcss,
  [IconName.NEXT]: SiNextdotjs,
  [IconName.REDUX]: SiRedux,
  [IconName.REACT_HOOK_FORM]: SiReacthookform,
  [IconName.MONSTERA]: GiMonsteraLeaf,
  [IconName.CYPRESS]: SiCypress,
  [IconName.PLAYWRIGHT]: SiPlaywright,
  [IconName.FIGMA]: SiFigma,
  [IconName.EXPO]: SiExpo,
  [IconName.AXIOS]: SiAxios,
  [IconName.GRAPHQL]: SiGraphql
};
